/**
 * Design-intent IR, MVP subset (architecture doc §5, §14).
 *
 * Conventions
 * - All numeric values are SI: metres, radians, kilograms. The original
 *   expression string (e.g. "50 mm") is kept alongside, so intent is never
 *   flattened to a number.
 * - Two layers: the intent layer (everything except `evidence`) is what gets
 *   hashed and versioned. The evidence layer (`Feature.evidence`) is derived
 *   from a CAD kernel, regenerable, and excluded from intent hashes.
 * - Ids are stable, document-unique strings chosen by the extractor
 *   ("f1", "f2", "l1", "c1"). Hashes are content-addressed over the intent.
 * - Features appear in rollback order; a feature may only reference features
 *   that precede it.
 * - Nothing extracted is thrown away: `ext.sw` carries the raw source payload.
 */

export const IR_VERSION = "0.1.0";

// ---------------------------------------------------------------------------
// Scalars
// ---------------------------------------------------------------------------

export type Vec2 = [number, number];
export type Vec3 = [number, number, number];
/** Row-major 4x4 homogeneous transform. */
export type Mat4 = number[];

export type Unit = "m" | "rad" | "kg" | "";

/** A value with its source expression. `parameter` links to a `Parameter.id`. */
export interface Quantity {
  expr: string;
  value: number;
  unit: Unit;
  parameter?: string;
}

// ---------------------------------------------------------------------------
// Fidelity (the fallback ladder, §6)
// ---------------------------------------------------------------------------

export type Rung =
  | "pending" // not yet attempted
  | "exact" // 1 direct
  | "composite" // 2 several native features
  | "featurescript" // 3 custom feature
  | "approximated" // 4 intent kept, geometry deviates
  | "geometry" // 5 geometry patch
  | "dropped"; // 6 not transferable

export interface Fidelity {
  rung: Rung;
  /** Human-readable reason for anything below "exact". */
  notes?: string;
  /** Measured deviation for "approximated" (metres). */
  deviation?: number;
}

// ---------------------------------------------------------------------------
// References (§8). Never a bare entity id: every Ref carries multiple
// independent resolvers so the target can pick the one that survives.
// ---------------------------------------------------------------------------

export type DatumName = "FRONT" | "TOP" | "RIGHT" | "ORIGIN";

/** A default datum plane or the origin point. */
export interface DatumRef {
  kind: "datum";
  name: DatumName;
}

/** Output of an earlier feature: a sketch region, a body, or a datum feature (plane). */
export interface FeatureOutputRef {
  kind: "feature-output";
  feature: string;
  role: "region" | "body" | "plane" | "axis" | "point";
  /** Which region when a sketch has several closed loops. */
  index?: number;
}

export type EntityType = "face" | "edge" | "vertex";

export interface FaceSignature {
  surface: "plane" | "cylinder" | "cone" | "torus" | "sphere" | "bspline";
  normal?: Vec3;
  /** Signed distance of a plane from the origin along `normal`. */
  offset?: number;
  axis?: Vec3;
  axisPoint?: Vec3;
  radius?: number;
  centroid?: Vec3;
  area?: number;
}

export interface EdgeSignature {
  curve: "line" | "circle" | "ellipse" | "bspline";
  radius?: number;
  center?: Vec3;
  midpoint?: Vec3;
  length?: number;
  direction?: Vec3;
}

export interface VertexSignature {
  point: Vec3;
}

/**
 * A face, edge or vertex. Resolver cascade, strongest first:
 * semantic role -> geometric signature -> adjacency -> spatial probe.
 */
export interface TopoRef {
  kind: "topo";
  entity: EntityType;
  /** Feature whose execution created this entity. */
  createdBy?: string;
  /**
   * Semantic role relative to `createdBy`, e.g. "capEnd", "capStart",
   * "sideWall", "sideWall:l3" (wall generated by sketch entity l3),
   * "edge:sideWall|capEnd" (edge between two roles). Free-form; the
   * mapping engine owns the vocabulary.
   */
  role?: string;
  /** Opaque id from the source CAD (SolidWorks persistent reference). */
  srcPersistId?: string;
  signature?: FaceSignature | EdgeSignature | VertexSignature;
  /** Hash of neighbouring signatures, to break symmetry ties. */
  adjacency?: string;
  /** A point on the entity, for spatial probing (metres). */
  probe?: Vec3;
}

export type Ref = DatumRef | FeatureOutputRef | TopoRef;

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------

export interface Parameter {
  id: string;
  /** Source name, e.g. "Width" or "D1@Sketch1". */
  name: string;
  scope: "global" | "part";
  expression: string;
  value: number;
  unit: Unit;
  /** Driven (read-only, computed) rather than driving. */
  driven: boolean;
}

// ---------------------------------------------------------------------------
// Sketches
// ---------------------------------------------------------------------------

export interface SketchEntityBase {
  id: string;
  construction: boolean;
  /** Source id (SolidWorks sketch segment name). */
  srcId?: string;
}

export interface SketchPoint extends SketchEntityBase {
  type: "point";
  p: Vec2;
}
export interface SketchLine extends SketchEntityBase {
  type: "line";
  p0: Vec2;
  p1: Vec2;
}
export interface SketchArc extends SketchEntityBase {
  type: "arc";
  center: Vec2;
  p0: Vec2;
  p1: Vec2;
  /** Counter-clockwise from p0 to p1 in sketch space. */
  ccw: boolean;
}
export interface SketchCircle extends SketchEntityBase {
  type: "circle";
  center: Vec2;
  r: number;
}
export interface SketchEllipse extends SketchEntityBase {
  type: "ellipse";
  center: Vec2;
  majorAxis: Vec2;
  minorRadius: number;
}
export interface SketchSpline extends SketchEntityBase {
  type: "spline";
  degree: number;
  controlPoints: Vec2[];
  knots: number[];
  weights?: number[];
}

export type SketchEntity =
  | SketchPoint
  | SketchLine
  | SketchArc
  | SketchCircle
  | SketchEllipse
  | SketchSpline;

/**
 * Argument to a constraint or dimension. Either a sketch entity id with an
 * optional sub-entity ("l1", "l1.start", "l1.end", "c1.center", "ORIGIN"),
 * or a Ref to model geometry outside the sketch (on-edge relations,
 * converted entities, locating dimensions to model edges).
 */
export type SketchArg = string | Ref;

export type ConstraintType =
  | "coincident"
  | "horizontal"
  | "vertical"
  | "parallel"
  | "perpendicular"
  | "tangent"
  | "concentric"
  | "equal"
  | "midpoint"
  | "symmetric"
  | "fix"
  | "collinear"
  | "pierce"
  | "onEntity";

export interface Constraint {
  type: ConstraintType;
  args: SketchArg[];
}

export type DimensionType =
  | "distance"
  | "horizontal"
  | "vertical"
  | "angle"
  | "radius"
  | "diameter";

export interface Dimension {
  /** Source full name, e.g. "D1@Sketch1". */
  id: string;
  type: DimensionType;
  args: SketchArg[];
  value: Quantity;
  driving: boolean;
}

// ---------------------------------------------------------------------------
// Features
// ---------------------------------------------------------------------------

export interface FeatureBase {
  id: string;
  /** Source feature name and type string. */
  src: { name: string; type?: string };
  suppressed: boolean;
  fidelity: Fidelity;
  /** Raw source payload, kept verbatim. */
  ext?: { sw?: unknown; [vendor: string]: unknown };
  /** Derived geometry after this feature. Not part of the intent hash. */
  evidence?: Evidence;
}

export interface SketchFeature extends FeatureBase {
  op: "sketch";
  plane: Ref;
  /** Sketch-to-model transform. Stored explicitly: systems derive it differently from a face. */
  transform: Mat4;
  entities: SketchEntity[];
  constraints: Constraint[];
  dimensions: Dimension[];
}

export type BooleanMode = "new" | "add" | "remove" | "intersect";

export type EndCondition =
  | { type: "blind"; depth: Quantity }
  | { type: "throughAll" }
  | { type: "upToNext" }
  | { type: "upToVertex"; vertex: Ref }
  | { type: "upToSurface"; face: Ref }
  | { type: "offsetFromSurface"; face: Ref; offset: Quantity; reverseOffset?: boolean }
  | { type: "midPlane"; depth: Quantity };

export interface ExtrudeFeature extends FeatureBase {
  op: "extrude";
  mode: BooleanMode;
  profile: Ref;
  /** Reverse the default direction (sketch normal). */
  flip: boolean;
  end: EndCondition;
  /** Second direction, opposite to the first. */
  end2?: EndCondition;
  draft?: { angle: Quantity; outward: boolean };
}

export interface RevolveFeature extends FeatureBase {
  op: "revolve";
  mode: BooleanMode;
  profile: Ref;
  /** A sketch line (as "sketchId:entityId"), a datum, or a model edge. */
  axis: Ref | { kind: "sketch-entity"; sketch: string; entity: string };
  angle: Quantity;
  flip: boolean;
}

export interface FilletFeature extends FeatureBase {
  op: "fillet";
  radius: Quantity;
  edges: Ref[];
  /** SolidWorks "tangent propagation": the selection mode, not just the edges. */
  tangentPropagation: boolean;
}

export type ChamferSpec =
  | { type: "equalDistance"; distance: Quantity }
  | { type: "twoDistances"; distance1: Quantity; distance2: Quantity; flip: boolean }
  | { type: "distanceAngle"; distance: Quantity; angle: Quantity; flip: boolean };

export interface ChamferFeature extends FeatureBase {
  op: "chamfer";
  spec: ChamferSpec;
  edges: Ref[];
  tangentPropagation: boolean;
}

export interface HoleFeature extends FeatureBase {
  op: "hole";
  style: "simple" | "counterbore" | "countersink";
  /** Points placing hole centres: sketch points or model vertices. */
  positions: Ref[];
  /** Face the hole starts from. */
  startFace: Ref;
  diameter: Quantity;
  end: EndCondition;
  counterbore?: { diameter: Quantity; depth: Quantity };
  countersink?: { diameter: Quantity; angle: Quantity };
  /** A blind hole that ends in a drill point: the included tip angle (118 deg for a standard drill). Absent for flat bottoms and through holes. */
  drillTip?: { angle: Quantity };
  /** Hole Wizard standard metadata, kept for mapping to Onshape hole tables. */
  standard?: { name: string; type?: string; size?: string };
}

export interface ShellFeature extends FeatureBase {
  op: "shell";
  thickness: Quantity;
  removeFaces: Ref[];
  outward: boolean;
}

export interface PatternDirection {
  direction: Ref | { kind: "sketch-entity"; sketch: string; entity: string };
  count: Quantity;
  spacing: Quantity;
  flip: boolean;
}

export interface LinearPatternFeature extends FeatureBase {
  op: "linearPattern";
  seeds: string[];
  direction1: PatternDirection;
  direction2?: PatternDirection;
  /** [i, j] instance indices omitted from the pattern. */
  skipped?: [number, number][];
}

export interface CircularPatternFeature extends FeatureBase {
  op: "circularPattern";
  seeds: string[];
  axis: Ref;
  count: Quantity;
  /** Total angle if `equalSpacing`, else angle between instances. */
  angle: Quantity;
  equalSpacing: boolean;
  flip: boolean;
  skipped?: number[];
}

export interface MirrorFeature extends FeatureBase {
  op: "mirror";
  seeds: string[];
  plane: Ref;
}

export type PlaneDefinition =
  | { type: "offset"; base: Ref; distance: Quantity; flip: boolean }
  | { type: "midPlane"; a: Ref; b: Ref }
  | { type: "angle"; base: Ref; axis: Ref; angle: Quantity; flip: boolean };

export interface PlaneFeature extends FeatureBase {
  op: "plane";
  definition: PlaneDefinition;
}

export type Feature =
  | SketchFeature
  | ExtrudeFeature
  | RevolveFeature
  | FilletFeature
  | ChamferFeature
  | HoleFeature
  | ShellFeature
  | LinearPatternFeature
  | CircularPatternFeature
  | MirrorFeature
  | PlaneFeature;

export type FeatureOp = Feature["op"];

// ---------------------------------------------------------------------------
// Evidence (§9 level 1): what the kernel produced after a feature.
// ---------------------------------------------------------------------------

export interface Evidence {
  bodyCount: number;
  /** m^3 */
  volume: number;
  /** m^2 */
  area: number;
  centerOfMass?: Vec3;
  bbox?: { min: Vec3; max: Vec3 };
  faceCount?: number;
  edgeCount?: number;
  vertexCount?: number;
  /** Histogram keyed by surface type. */
  faceTypes?: Partial<Record<FaceSignature["surface"], number>>;
  /** Content hash of an exported B-rep (Parasolid/STEP) stored as a blob. */
  brepHash?: string;
  /** Content hashes of rendered views (PNG) of the source model at this rollback step. */
  views?: string[];
}

// ---------------------------------------------------------------------------
// Document
// ---------------------------------------------------------------------------

export interface Source {
  cad: "solidworks" | "onshape" | "fusion" | "inventor" | "freecad" | "other";
  version?: string;
  fileName?: string;
  /** sha256 of the source file. */
  fileHash?: string;
  extractedAt?: string;
}

export interface PartStudio {
  id: string;
  name: string;
  features: Feature[];
}

/**
 * Level 3 evidence (§9): the extractor changed one driving dimension or
 * parameter in the source, rebuilt, and recorded what the kernel produced.
 * The builder applies the same change in the target and compares. Derived,
 * like `Feature.evidence`: not part of the intent hash.
 */
export interface BehaviorEvidence {
  /** Dimension id ("D1@Sketch1") or parameter id. */
  target: string;
  /** New expression as typed in the source, e.g. "55 mm". */
  expression: string;
  /** Final-model evidence after the change and rebuild. */
  evidence: Evidence;
  /** Optional plain-language expectation, for the report. */
  expectation?: string;
}

export interface Document {
  irVersion: typeof IR_VERSION;
  source: Source;
  /** SolidWorks custom properties (part number, material, description...). Context for the translator. */
  customProperties?: Record<string, string>;
  parameters: Parameter[];
  partStudio: PartStudio;
  /** Source-side results of perturbing driving dimensions (§9 Level 3). Evidence layer. */
  behaviorEvidence?: BehaviorEvidence[];
  /** Reserved: configurations as overlays (§5). Empty in the MVP. */
  configurations?: never[];
  /** Reserved: assemblies and mates. Empty in the MVP. */
  assemblies?: never[];
}
