export { buildDocument, DATUM_REMAP } from "./builder.ts";
export type { AttemptRecord, BuildOptions, BuildReport, FeatureRecord } from "./builder.ts";
export { OnshapeClient } from "./client/client.ts";
export type { OnshapeApi } from "./client/api.ts";
export { OnshapeHttp, OnshapeHttpError, OnshapeQuotaError } from "./client/http.ts";
export { basicAuth, hmacAuth } from "./client/auth.ts";
export type * from "./client/types.ts";
export { loadConfig, loadClaudeConfig, loadEnvFiles } from "./env.ts";
export type { OnshapeConfig, ClaudeEnv } from "./env.ts";
export { decodeFsValue } from "./fs/values.ts";
export { topologyScript, bodyStatsScript } from "./fs/scripts.ts";
export { queryTopology, queryBodyStats, frameOf } from "./fs/topology.ts";
export type { Candidate, BodyStats } from "./fs/topology.ts";
export { Executor, AmbiguousSelectionError, ExecutionError } from "./plan/executor.ts";
export type { StepContext, StepExecution, OpResult, SelectionRecord } from "./plan/executor.ts";
export { PLAN_VERSION } from "./plan/types.ts";
export type { BuildPlan, PlanStep, Op, Selection, BehaviorTest } from "./plan/types.ts";
export { validateStepProposal, validateBehaviorTests, PlanValidationError } from "./plan/validate.ts";
export { stepProposalSchema, behaviorTestsSchema } from "./plan/schema.ts";
export { RulePlanner, RulePlannerError } from "./planner/rules.ts";
export { ReplayPlanner } from "./planner/replay.ts";
export { ClaudePlanner, CLAUDE_PROMPT_VERSION } from "./planner/claude.ts";
export type { Planner, StepRequest, Feedback, LlmUsage, StepProposal } from "./planner/types.ts";
export { proposeDirect, proposableOps, ProposalError } from "./proposers/index.ts";
export { composeSketch, SketchComposeError } from "./sketch/compose.ts";
export { rankCandidates, resolveTopo, ResolveError } from "./resolver.ts";
export type { Resolution, ResolveOptions, Decision, RankedCandidate } from "./resolver.ts";
export { level1Checks, hardFailures, DEFAULT_TOLERANCES } from "./validate.ts";
export type { Check, Tolerances } from "./validate.ts";
export { renderMarkdown } from "./report.ts";
export { exampleLibraryPrompt, EXAMPLE_INDEX } from "./examples/library.ts";
export * as geometry from "./geometry.ts";
export { lengthExpression, angleExpression, variableName } from "./expression.ts";
